#### a라는 것에 1을 assign / type(a) : class a의 타입을 보여줌
    int:정수형/float:실수형

In [17]:
a = 1; print(type(a))

<class 'int'>


In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [14]:
a = 1.0

In [15]:
type(a)

float

#### a의 타입을 float에서 int로 바꾸는 과정 그래도 a는 1.1로 입력되어 있음. a를 int로 바꿔서 결과를 내는 것임

In [16]:
int(a)

1

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


#### list 
    -대괄호로 감싸고 콤마로 구분

In [17]:
a=[1,2,3]

In [18]:
type(a)

list

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


#### tuple 
    -값을 바꿀 수 없음. 
    -괄호로 감싸지만 괄호를 생략해도 됨. 
    -한개의 요소만을 가질 때는 요소 뒤에 콤마를 반드시 붙여야 한다

In [20]:
a = (1,2,3,4)

In [21]:
type(a)

tuple

In [22]:
b = (1,)

In [23]:
type(b)

tuple

#### Dictionary
    -대괄호를 사용하여 만듬 
    -"a"가 표제어 , "apple"이 content 로 pairwise하게 이루어진다
    -a라는 variable에서 "a"를 찾아 print하라.
    -단순히 index로만 접근할 때는 list로, 하나하나 정의하고 싶을 때는 dictionary 방식으로 만든다.

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])a

<class 'dict'>
apple


In [1]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

### import
    하드디스크에 넣어놓는 내용을 메모리에 올리는 과정
    폴더로 numpy라는 게 있을 때 그 하위에 함수들이 존재   
    필요한 기능,함수가 numpy라는 패키지 혹은 라이브러리에 있구나
    패키지(라이브러리).function 의 형식으로 쓴다.
    numpy : 행렬을 처리하는 기능이 없는 파이썬에서 비슷한 기능을 수행한다.
    

In [3]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [24]:
#실제 행렬계산이 아님

In [6]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


#### 실제 행렬의 기능을 하는 함수는 matrix

In [8]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [9]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### c.T는 c를 transpose한 것임.

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

#### String

In [12]:
s = 'abcdef'

In [13]:
print(type(s))

<class 'str'>
